# Generated by Django 5.2.8 on 2025-11-26 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_menuitem_restaurant'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='image_url',
            field=models.URLField(blank=True, help_text='External image URL (takes precedence over uploaded image)', max_length=500, null=True),
        ),
    ]
