# Generated by Django 5.2.8 on 2025-11-22 10:20

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(help_text='Full name for delivery and personalization', max_length=100)),
                ('phone_number', models.CharField(help_text='Phone number for order notifications and delivery contact', max_length=20, validators=[django.core.validators.RegexValidator(message='Phone number must be entered in the format: +999999999. Up to 15 digits allowed.', regex='^\\+?1?\\d{9,15}$')])),
                ('address', models.TextField(blank=True, help_text='Delivery address for food orders')),
                ('city', models.CharField(blank=True, help_text='City for delivery', max_length=100)),
                ('postal_code', models.CharField(blank=True, help_text='Postal/ZIP code for delivery', max_length=20)),
                ('dietary_preferences', models.CharField(blank=True, help_text='Dietary preferences (e.g., vegetarian, vegan, allergies)', max_length=200)),
                ('profile_picture', models.ImageField(blank=True, help_text='Profile picture for personalization', null=True, upload_to='profile_pics/')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When the profile was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When the profile was last updated')),
                ('user', models.OneToOneField(help_text='Link to the Django User account', on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Profile',
                'verbose_name_plural': 'User Profiles',
                'ordering': ['-created_at'],
            },
        ),
    ]
