# Generated by Django 5.2.8 on 2025-11-24 05:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
        ('orders', '0003_order_user'),
        ('restaurant', '0004_managerloginlog'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RestaurantReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveSmallIntegerField(choices=[(1, '1 Stars'), (2, '2 Stars'), (3, '3 Stars'), (4, '4 Stars'), (5, '5 Stars')], help_text='Rating from 1 to 5 stars')),
                ('title', models.CharField(help_text='Review title or summary', max_length=200)),
                ('comment', models.TextField(help_text='Detailed review comment')),
                ('food_quality', models.PositiveSmallIntegerField(choices=[(1, '1 Stars'), (2, '2 Stars'), (3, '3 Stars'), (4, '4 Stars'), (5, '5 Stars')], default=5, help_text='Food quality rating')),
                ('delivery_speed', models.PositiveSmallIntegerField(choices=[(1, '1 Stars'), (2, '2 Stars'), (3, '3 Stars'), (4, '4 Stars'), (5, '5 Stars')], default=5, help_text='Delivery speed rating')),
                ('value_for_money', models.PositiveSmallIntegerField(choices=[(1, '1 Stars'), (2, '2 Stars'), (3, '3 Stars'), (4, '4 Stars'), (5, '5 Stars')], default=5, help_text='Value for money rating')),
                ('is_approved', models.BooleanField(default=True, help_text='Whether review is approved for public display')),
                ('is_verified_purchase', models.BooleanField(default=False, help_text='Whether this review is from a verified order')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When the review was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When the review was last updated')),
                ('order', models.ForeignKey(blank=True, help_text='Order associated with this review', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviews', to='orders.order')),
                ('restaurant', models.ForeignKey(help_text='Restaurant being reviewed', on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='restaurant.restaurant')),
                ('user', models.ForeignKey(help_text='Customer who wrote the review', on_delete=django.db.models.deletion.CASCADE, related_name='restaurant_reviews', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Restaurant Review',
                'verbose_name_plural': 'Restaurant Reviews',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['restaurant', '-created_at'], name='customer_re_restaur_3544da_idx'), models.Index(fields=['user', '-created_at'], name='customer_re_user_id_80798c_idx'), models.Index(fields=['is_approved'], name='customer_re_is_appr_48332d_idx')],
                'unique_together': {('user', 'restaurant', 'order')},
            },
        ),
        migrations.CreateModel(
            name='Wishlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When the restaurant was added to wishlist')),
                ('restaurant', models.ForeignKey(help_text='Restaurant added to wishlist', on_delete=django.db.models.deletion.CASCADE, related_name='wishlisted_by', to='restaurant.restaurant')),
                ('user', models.ForeignKey(help_text='Customer who owns this wishlist item', on_delete=django.db.models.deletion.CASCADE, related_name='wishlist_items', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Wishlist Item',
                'verbose_name_plural': 'Wishlist Items',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='customer_wi_user_id_4acfdc_idx')],
                'unique_together': {('user', 'restaurant')},
            },
        ),
    ]
