# Generated by Django 5.2.8 on 2025-11-24 07:49

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_restaurantreview_wishlist'),
        ('menu', '0002_menuitem_restaurant'),
        ('orders', '0003_order_user'),
        ('restaurant', '0004_managerloginlog'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MenuItemReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(help_text='Menu item rating from 1 to 5 stars', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('comment', models.TextField(blank=True, help_text='Detailed review text for the menu item')),
                ('taste', models.IntegerField(blank=True, help_text='Taste rating (1-5)', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('presentation', models.IntegerField(blank=True, help_text='Presentation rating (1-5)', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('portion_size', models.IntegerField(blank=True, help_text='Portion size rating (1-5)', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('is_flagged', models.BooleanField(default=False, help_text='Review has been flagged for moderation')),
                ('is_hidden', models.BooleanField(default=False, help_text='Review is hidden from public view')),
                ('flag_reason', models.TextField(blank=True, help_text='Reason why this review was flagged')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When the review was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When the review was last updated')),
            ],
            options={
                'verbose_name': 'Menu Item Review',
                'verbose_name_plural': 'Menu Item Reviews',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReviewFlag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(choices=[('spam', 'Spam or fake content'), ('offensive', 'Offensive language'), ('inappropriate', 'Inappropriate content'), ('off_topic', 'Off-topic review'), ('duplicate', 'Duplicate review'), ('other', 'Other reason')], help_text='Reason for flagging the review', max_length=20)),
                ('description', models.TextField(blank=True, help_text='Additional details about the flag')),
                ('is_resolved', models.BooleanField(default=False, help_text='Whether this flag has been resolved by admin')),
                ('admin_notes', models.TextField(blank=True, help_text='Admin notes about the resolution')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When the review was flagged')),
                ('resolved_at', models.DateTimeField(blank=True, help_text='When the flag was resolved', null=True)),
            ],
            options={
                'verbose_name': 'Review Flag',
                'verbose_name_plural': 'Review Flags',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReviewResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('response', models.TextField(help_text='Response text from restaurant owner')),
                ('is_public', models.BooleanField(default=True, help_text='Whether this response is visible to customers')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When the response was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When the response was last updated')),
            ],
            options={
                'verbose_name': 'Review Response',
                'verbose_name_plural': 'Review Responses',
                'ordering': ['-created_at'],
            },
        ),
        migrations.RemoveIndex(
            model_name='restaurantreview',
            name='customer_re_restaur_3544da_idx',
        ),
        migrations.RemoveIndex(
            model_name='restaurantreview',
            name='customer_re_user_id_80798c_idx',
        ),
        migrations.RemoveIndex(
            model_name='restaurantreview',
            name='customer_re_is_appr_48332d_idx',
        ),
        migrations.AlterUniqueTogether(
            name='restaurantreview',
            unique_together={('user', 'order', 'restaurant')},
        ),
        migrations.AddField(
            model_name='restaurantreview',
            name='flag_reason',
            field=models.TextField(blank=True, help_text='Reason why this review was flagged'),
        ),
        migrations.AddField(
            model_name='restaurantreview',
            name='is_flagged',
            field=models.BooleanField(default=False, help_text='Review has been flagged for moderation'),
        ),
        migrations.AddField(
            model_name='restaurantreview',
            name='is_hidden',
            field=models.BooleanField(default=False, help_text='Review is hidden from public view (moderation action)'),
        ),
        migrations.AddField(
            model_name='restaurantreview',
            name='service_quality',
            field=models.IntegerField(blank=True, help_text='Service quality rating (1-5)', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AlterField(
            model_name='restaurantreview',
            name='comment',
            field=models.TextField(help_text='Detailed review text from customer'),
        ),
        migrations.AlterField(
            model_name='restaurantreview',
            name='delivery_speed',
            field=models.IntegerField(blank=True, help_text='Delivery speed rating (1-5)', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AlterField(
            model_name='restaurantreview',
            name='food_quality',
            field=models.IntegerField(blank=True, help_text='Food quality rating (1-5)', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AlterField(
            model_name='restaurantreview',
            name='is_verified_purchase',
            field=models.BooleanField(default=True, help_text='Indicates this review is from a verified purchase'),
        ),
        migrations.AlterField(
            model_name='restaurantreview',
            name='order',
            field=models.ForeignKey(blank=True, help_text='Order that enabled this review (verified purchase)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='restaurant_reviews', to='orders.order'),
        ),
        migrations.AlterField(
            model_name='restaurantreview',
            name='rating',
            field=models.IntegerField(help_text='Restaurant rating from 1 to 5 stars', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AlterField(
            model_name='restaurantreview',
            name='title',
            field=models.CharField(blank=True, help_text='Optional review title', max_length=100),
        ),
        migrations.AlterField(
            model_name='restaurantreview',
            name='value_for_money',
            field=models.IntegerField(blank=True, help_text='Value for money rating (1-5)', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AddIndex(
            model_name='restaurantreview',
            index=models.Index(fields=['restaurant', 'created_at'], name='customer_re_restaur_27e4b3_idx'),
        ),
        migrations.AddIndex(
            model_name='restaurantreview',
            index=models.Index(fields=['rating'], name='customer_re_rating_1168a8_idx'),
        ),
        migrations.AddIndex(
            model_name='restaurantreview',
            index=models.Index(fields=['is_flagged'], name='customer_re_is_flag_e91071_idx'),
        ),
        migrations.AddField(
            model_name='menuitemreview',
            name='menu_item',
            field=models.ForeignKey(help_text='Menu item being reviewed', on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='menu.menuitem'),
        ),
        migrations.AddField(
            model_name='menuitemreview',
            name='order',
            field=models.ForeignKey(blank=True, help_text='Order that contained this menu item (verified purchase)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='menu_item_reviews', to='orders.order'),
        ),
        migrations.AddField(
            model_name='menuitemreview',
            name='user',
            field=models.ForeignKey(help_text='Customer who wrote the review', on_delete=django.db.models.deletion.CASCADE, related_name='menu_item_reviews', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='reviewflag',
            name='flagged_by',
            field=models.ForeignKey(help_text='User who flagged the review', on_delete=django.db.models.deletion.CASCADE, related_name='review_flags', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='reviewflag',
            name='menu_item_review',
            field=models.ForeignKey(blank=True, help_text='Menu item review being flagged', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='flags', to='customer.menuitemreview'),
        ),
        migrations.AddField(
            model_name='reviewflag',
            name='restaurant_review',
            field=models.ForeignKey(blank=True, help_text='Restaurant review being flagged', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='flags', to='customer.restaurantreview'),
        ),
        migrations.AddField(
            model_name='reviewresponse',
            name='menu_item_review',
            field=models.ForeignKey(blank=True, help_text='Menu item review being responded to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='customer.menuitemreview'),
        ),
        migrations.AddField(
            model_name='reviewresponse',
            name='responder',
            field=models.ForeignKey(help_text='Restaurant owner/manager who wrote the response', on_delete=django.db.models.deletion.CASCADE, related_name='review_responses', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='reviewresponse',
            name='restaurant_review',
            field=models.ForeignKey(blank=True, help_text='Restaurant review being responded to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='customer.restaurantreview'),
        ),
        migrations.RemoveField(
            model_name='restaurantreview',
            name='is_approved',
        ),
        migrations.AddIndex(
            model_name='menuitemreview',
            index=models.Index(fields=['menu_item', 'created_at'], name='customer_me_menu_it_731f48_idx'),
        ),
        migrations.AddIndex(
            model_name='menuitemreview',
            index=models.Index(fields=['rating'], name='customer_me_rating_6cdc62_idx'),
        ),
        migrations.AddIndex(
            model_name='menuitemreview',
            index=models.Index(fields=['is_flagged'], name='customer_me_is_flag_220445_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='menuitemreview',
            unique_together={('user', 'order', 'menu_item')},
        ),
        migrations.AlterUniqueTogether(
            name='reviewflag',
            unique_together={('flagged_by', 'menu_item_review'), ('flagged_by', 'restaurant_review')},
        ),
    ]
