# Generated by Django 5.2.8 on 2025-11-24 08:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0003_menuitemreview_reviewflag_reviewresponse_and_more'),
        ('orders', '0003_order_user'),
        ('restaurant', '0004_managerloginlog'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='restaurantreview',
            name='customer_re_restaur_27e4b3_idx',
        ),
        migrations.RemoveIndex(
            model_name='restaurantreview',
            name='customer_re_rating_1168a8_idx',
        ),
        migrations.RemoveIndex(
            model_name='restaurantreview',
            name='customer_re_is_flag_e91071_idx',
        ),
        migrations.AlterUniqueTogether(
            name='restaurantreview',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='restaurantreview',
            name='is_approved',
            field=models.BooleanField(default=True, help_text='Whether review is approved for public display'),
        ),
        migrations.AlterField(
            model_name='restaurantreview',
            name='comment',
            field=models.TextField(help_text='Detailed review comment'),
        ),
        migrations.AlterField(
            model_name='restaurantreview',
            name='delivery_speed',
            field=models.PositiveSmallIntegerField(choices=[(1, '1 Stars'), (2, '2 Stars'), (3, '3 Stars'), (4, '4 Stars'), (5, '5 Stars')], default=5, help_text='Delivery speed rating'),
        ),
        migrations.AlterField(
            model_name='restaurantreview',
            name='flag_reason',
            field=models.TextField(blank=True, help_text='Reason why this review was flagged', null=True),
        ),
        migrations.AlterField(
            model_name='restaurantreview',
            name='food_quality',
            field=models.PositiveSmallIntegerField(choices=[(1, '1 Stars'), (2, '2 Stars'), (3, '3 Stars'), (4, '4 Stars'), (5, '5 Stars')], default=5, help_text='Food quality rating'),
        ),
        migrations.AlterField(
            model_name='restaurantreview',
            name='is_flagged',
            field=models.BooleanField(default=False, help_text='Whether this review has been flagged for moderation'),
        ),
        migrations.AlterField(
            model_name='restaurantreview',
            name='is_hidden',
            field=models.BooleanField(default=False, help_text='Whether this review is hidden from public view'),
        ),
        migrations.AlterField(
            model_name='restaurantreview',
            name='is_verified_purchase',
            field=models.BooleanField(default=False, help_text='Whether this review is from a verified order'),
        ),
        migrations.AlterField(
            model_name='restaurantreview',
            name='order',
            field=models.ForeignKey(blank=True, help_text='Order associated with this review', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviews', to='orders.order'),
        ),
        migrations.AlterField(
            model_name='restaurantreview',
            name='rating',
            field=models.PositiveSmallIntegerField(choices=[(1, '1 Stars'), (2, '2 Stars'), (3, '3 Stars'), (4, '4 Stars'), (5, '5 Stars')], help_text='Rating from 1 to 5 stars'),
        ),
        migrations.AlterField(
            model_name='restaurantreview',
            name='service_quality',
            field=models.PositiveSmallIntegerField(choices=[(1, '1 Stars'), (2, '2 Stars'), (3, '3 Stars'), (4, '4 Stars'), (5, '5 Stars')], default=5, help_text='Service quality rating'),
        ),
        migrations.AlterField(
            model_name='restaurantreview',
            name='title',
            field=models.CharField(help_text='Review title or summary', max_length=200),
        ),
        migrations.AlterField(
            model_name='restaurantreview',
            name='value_for_money',
            field=models.PositiveSmallIntegerField(choices=[(1, '1 Stars'), (2, '2 Stars'), (3, '3 Stars'), (4, '4 Stars'), (5, '5 Stars')], default=5, help_text='Value for money rating'),
        ),
        migrations.AlterUniqueTogether(
            name='restaurantreview',
            unique_together={('user', 'restaurant', 'order')},
        ),
        migrations.AddIndex(
            model_name='restaurantreview',
            index=models.Index(fields=['restaurant', '-created_at'], name='customer_re_restaur_3544da_idx'),
        ),
        migrations.AddIndex(
            model_name='restaurantreview',
            index=models.Index(fields=['user', '-created_at'], name='customer_re_user_id_80798c_idx'),
        ),
        migrations.AddIndex(
            model_name='restaurantreview',
            index=models.Index(fields=['is_approved'], name='customer_re_is_appr_48332d_idx'),
        ),
    ]
