# Generated by Django 5.2.8 on 2025-11-26 06:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0004_remove_restaurantreview_customer_re_restaur_27e4b3_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transactional_emails', models.BooleanField(default=True, help_text='Order confirmations, status updates, password resets')),
                ('promotional_emails', models.BooleanField(default=False, help_text='Marketing emails, special offers, new restaurant announcements')),
                ('newsletter_emails', models.BooleanField(default=False, help_text='Weekly newsletter with food trends and featured restaurants')),
                ('review_emails', models.BooleanField(default=True, help_text='Emails asking for reviews after orders')),
                ('restaurant_updates', models.BooleanField(default=True, help_text='Updates from restaurants where user has ordered')),
                ('consent_date', models.DateTimeField(auto_now_add=True, help_text='When user first set their email preferences')),
                ('last_updated', models.DateTimeField(auto_now=True, help_text='When email preferences were last updated')),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='IP address when preferences were last updated', null=True)),
                ('user', models.OneToOneField(help_text='User who owns these email preferences', on_delete=django.db.models.deletion.CASCADE, related_name='email_preferences', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Email Preference',
                'verbose_name_plural': 'Email Preferences',
            },
        ),
    ]
