# Generated by Django 5.2.8 on 2025-11-28 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0005_emailpreference'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('customer', 'Customer'), ('restaurant_owner', 'Restaurant Owner'), ('manager', 'Manager'), ('admin', 'Administrator')], default='customer', help_text='Primary role of the user in the system', max_length=20),
        ),
    ]
