# Generated by Django 5.2.8 on 2025-11-30 17:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0006_add_user_role_field'),
        ('orders', '0006_order_payment_method_order_payment_status_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='points_balance',
            field=models.PositiveIntegerField(default=0, help_text='Current loyalty points balance for the user'),
        ),
        migrations.CreateModel(
            name='LoyaltyTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('earned', 'Points Earned'), ('redeemed', 'Points Redeemed'), ('expired', 'Points Expired'), ('manual', 'Manual Adjustment'), ('refunded', 'Points Refunded')], help_text='Type of point transaction', max_length=20)),
                ('points', models.IntegerField(help_text='Points amount (positive for earned, negative for redeemed/expired)')),
                ('balance_after', models.IntegerField(help_text="User's points balance after this transaction")),
                ('description', models.TextField(blank=True, help_text='Description of why points were awarded or deducted')),
                ('expires_at', models.DateTimeField(blank=True, help_text='When these points will expire (for earned points)', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When the transaction occurred')),
                ('order', models.ForeignKey(blank=True, help_text='Order that triggered this transaction (if applicable)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='loyalty_transactions', to='orders.order')),
                ('user', models.ForeignKey(help_text='User who owns this transaction', on_delete=django.db.models.deletion.CASCADE, related_name='loyalty_transactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Loyalty Transaction',
                'verbose_name_plural': 'Loyalty Transactions',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'created_at'], name='customer_lo_user_id_adce45_idx'), models.Index(fields=['transaction_type'], name='customer_lo_transac_a126ba_idx'), models.Index(fields=['expires_at'], name='customer_lo_expires_450469_idx')],
            },
        ),
    ]
