# Generated by Django 5.2.8 on 2025-11-30 17:23

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0007_userprofile_points_balance_loyaltytransaction'),
        ('orders', '0006_order_payment_method_order_payment_status_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='loyaltytransaction',
            index=models.Index(fields=['balance_after'], name='customer_lo_balance_5870f3_idx'),
        ),
    ]
