# Generated by Django 5.2.8 on 2025-12-07 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0008_loyaltytransaction_customer_lo_balance_5870f3_idx'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='address',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='full_name',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='phone_number',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='_address_encrypted',
            field=models.TextField(blank=True, help_text='Encrypted delivery address for food orders', null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='_full_name_encrypted',
            field=models.TextField(blank=True, help_text='Encrypted full name for delivery and personalization', null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='_phone_number_encrypted',
            field=models.TextField(blank=True, help_text='Encrypted phone number for order notifications and delivery contact', null=True),
        ),
    ]
