# Generated by Django 5.2.8 on 2025-12-07 09:03

from django.db import migrations


def encrypt_existing_user_data(apps, schema_editor):
    """
    Encrypt existing plaintext user data before schema migration removes old fields.
    
    This function reads existing plaintext data from the old fields,
    encrypts it using the EncryptionManager, and stores it in the new encrypted fields.
    This migration MUST run before the schema migration that removes old fields.
    """
    from core.encryption import EncryptionManager
    
    UserProfile = apps.get_model('customer', 'UserProfile')
    
    # Process in batches to avoid memory issues with large datasets
    batch_size = 100
    total = UserProfile.objects.count()
    processed = 0
    errors = 0
    
    print(f"Starting encryption of {total} user profiles...")
    
    for profile in UserProfile.objects.all().iterator(chunk_size=batch_size):
        try:
            # Get original field values if they exist
            original_full_name = None
            original_phone = None
            original_address = None
            
            # Check if old fields still exist (they should at this point)
            if hasattr(profile, '_full_name_encrypted_original'):
                original_full_name = profile._full_name_encrypted_original
            if hasattr(profile, '_phone_number_encrypted_original'):
                original_phone = profile._phone_number_encrypted_original
            if hasattr(profile, '_address_encrypted_original'):
                original_address = profile._address_encrypted_original
            
            # If original fields don't exist, try to get from current encrypted fields
            # This handles case where migration is re-run
            if not original_full_name and profile._full_name_encrypted:
                try:
                    original_full_name = EncryptionManager.decrypt(profile._full_name_encrypted)
                except:
                    original_full_name = profile._full_name_encrypted  # Already encrypted
            
            if not original_phone and profile._phone_number_encrypted:
                try:
                    original_phone = EncryptionManager.decrypt(profile._phone_number_encrypted)
                except:
                    original_phone = profile._phone_number_encrypted  # Already encrypted
            
            if not original_address and profile._address_encrypted:
                try:
                    original_address = EncryptionManager.decrypt(profile._address_encrypted)
                except:
                    original_address = profile._address_encrypted  # Already encrypted
            
            # Encrypt and store in new fields
            if original_full_name:
                profile._full_name_encrypted = EncryptionManager.encrypt(original_full_name)
            
            if original_phone:
                profile._phone_number_encrypted = EncryptionManager.encrypt(original_phone)
            
            if original_address:
                profile._address_encrypted = EncryptionManager.encrypt(original_address)
            
            profile.save()
            processed += 1
            
            # Progress reporting
            if processed % 10 == 0:
                print(f"Processed {processed}/{total} profiles...")
                
        except Exception as e:
            errors += 1
            print(f"Error encrypting profile {profile.id}: {str(e)}")
            # Continue processing other profiles
            continue
    
    print(f"Encryption complete! Processed: {processed}, Errors: {errors}")


def reverse_encryption(apps, schema_editor):
    """
    Reverse migration - decrypt data back to plaintext.
    
    WARNING: This should only be used if you need to rollback the encryption system.
    This will decrypt all data back to plaintext and store in original field names.
    """
    from core.encryption import EncryptionManager
    
    UserProfile = apps.get_model('customer', 'UserProfile')
    
    print("Decrypting user profiles back to plaintext...")
    
    for profile in UserProfile.objects.all():
        try:
            # Decrypt fields back to plaintext
            if profile._full_name_encrypted:
                profile._full_name_encrypted_original = EncryptionManager.decrypt(profile._full_name_encrypted)
            
            if profile._phone_number_encrypted:
                profile._phone_number_encrypted_original = EncryptionManager.decrypt(profile._phone_number_encrypted)
            
            if profile._address_encrypted:
                profile._address_encrypted_original = EncryptionManager.decrypt(profile._address_encrypted)
            
            profile.save()
            
        except Exception as e:
            print(f"Error decrypting profile {profile.id}: {str(e)}")
            continue


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0009_add_encrypted_fields'),
    ]
    
    operations = [
        migrations.RunPython(
            encrypt_existing_user_data,
            reverse_code=reverse_encryption
        ),
    ]
