# Generated by Django 3.2.25 on 2025-07-01 16:54

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attraction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the attraction', max_length=200)),
                ('description', models.TextField(help_text='Detailed description of the attraction')),
                ('category', models.CharField(choices=[('landmark', 'Landmark'), ('museum', 'Museum'), ('park', 'Park'), ('beach', 'Beach'), ('mountain', 'Mountain'), ('historical', 'Historical Site'), ('religious', 'Religious Site'), ('shopping', 'Shopping'), ('entertainment', 'Entertainment'), ('nature', 'Nature'), ('adventure', 'Adventure'), ('other', 'Other')], default='other', help_text='Category of the attraction', max_length=50)),
                ('address', models.TextField(blank=True, help_text='Physical address of the attraction')),
                ('latitude', models.FloatField(blank=True, help_text='Latitude coordinate', null=True)),
                ('longitude', models.FloatField(blank=True, help_text='Longitude coordinate', null=True)),
                ('opening_hours', models.TextField(blank=True, help_text='Opening hours information')),
                ('entry_fee', models.CharField(blank=True, help_text='Information about entry fees', max_length=255)),
                ('website', models.URLField(blank=True, help_text='Official website of the attraction')),
                ('contact_phone', models.CharField(blank=True, help_text='Contact phone number', max_length=50)),
                ('contact_email', models.EmailField(blank=True, help_text='Contact email address', max_length=254)),
                ('is_featured', models.BooleanField(default=False, help_text='Whether this is a featured attraction')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When the attraction was added')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When the attraction was last updated')),
            ],
            options={
                'verbose_name': 'Attraction',
                'verbose_name_plural': 'Attractions',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='AttractionImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(help_text='The image file', upload_to='attractions/')),
                ('caption', models.CharField(blank=True, help_text='Optional caption for the image', max_length=255)),
                ('is_primary', models.BooleanField(default=False, help_text='Whether this is the primary image for the attraction')),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order for the image')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When the image was uploaded')),
            ],
            options={
                'verbose_name': 'Attraction Image',
                'verbose_name_plural': 'Attraction Images',
                'ordering': ['order', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='Destination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the destination', max_length=200)),
                ('slug', models.SlugField(help_text='URL-friendly version of the name', max_length=200, unique=True)),
                ('description', models.TextField(help_text='Detailed description of the destination')),
                ('short_description', models.CharField(blank=True, help_text='Brief description for listings and previews', max_length=255)),
                ('latitude', models.FloatField(blank=True, help_text='Latitude coordinate of the destination', null=True)),
                ('longitude', models.FloatField(blank=True, help_text='Longitude coordinate of the destination', null=True)),
                ('address', models.TextField(blank=True, help_text='Physical address of the destination')),
                ('city', models.CharField(blank=True, help_text='City where the destination is located', max_length=100)),
                ('country', models.CharField(help_text='Country where the destination is located', max_length=100)),
                ('postal_code', models.CharField(blank=True, help_text='Postal or ZIP code of the destination', max_length=20)),
                ('is_featured', models.BooleanField(default=False, help_text='Whether this is a featured destination')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this destination is currently active')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When the destination was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When the destination was last updated')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='DestinationImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(help_text='The image file', upload_to='destinations/')),
                ('caption', models.CharField(blank=True, help_text='Optional caption for the image', max_length=255)),
                ('is_primary', models.BooleanField(default=False, help_text='Whether this is the primary image for the destination')),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order for the image')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When the image was uploaded')),
            ],
            options={
                'verbose_name': 'Destination Image',
                'verbose_name_plural': 'Destination Images',
                'ordering': ['order', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the region', max_length=100, verbose_name='name')),
                ('code', models.CharField(blank=True, help_text='Short code for the region (e.g., EU, NA, SEA)', max_length=10, null=True, unique=True)),
                ('is_active', models.BooleanField(default=True, help_text='Whether the region is active and visible to users')),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order (lower numbers shown first)')),
                ('slug', models.SlugField(help_text='URL-friendly version of the name', max_length=100, unique=True)),
                ('description', models.TextField(blank=True, help_text='Description of the region', verbose_name='description')),
                ('image', models.ImageField(blank=True, help_text='Representative image of the region', null=True, upload_to='regions/')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, help_text='When this record was created', verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When the region was last updated')),
            ],
            options={
                'verbose_name': 'region',
                'verbose_name_plural': 'regions',
                'db_table': 'destinations_region',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Season',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the season (e.g., Summer, Monsoon)', max_length=50)),
                ('start_month', models.PositiveSmallIntegerField(help_text='Starting month (1-12)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)])),
                ('end_month', models.PositiveSmallIntegerField(help_text='Ending month (1-12)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)])),
                ('description', models.TextField(help_text='Description of what to expect during this season')),
                ('average_temperature', models.CharField(blank=True, help_text='Average temperature range during this season', max_length=50)),
                ('is_peak_season', models.BooleanField(default=False, help_text='Whether this is a peak travel season')),
                ('destination', models.ForeignKey(help_text='The destination this season applies to', on_delete=django.db.models.deletion.CASCADE, related_name='seasons', to='destinations.destination')),
            ],
            options={
                'ordering': ['start_month'],
            },
        ),
        migrations.AddIndex(
            model_name='region',
            index=models.Index(fields=['code'], name='region_code_idx'),
        ),
        migrations.AddIndex(
            model_name='region',
            index=models.Index(fields=['is_active'], name='region_active_idx'),
        ),
        migrations.AddIndex(
            model_name='region',
            index=models.Index(fields=['order'], name='region_order_idx'),
        ),
        migrations.AddField(
            model_name='destinationimage',
            name='destination',
            field=models.ForeignKey(help_text='The destination this image belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='images', to='destinations.destination'),
        ),
        migrations.AddField(
            model_name='destination',
            name='region',
            field=models.ForeignKey(blank=True, help_text='Region this destination belongs to', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='destinations', to='destinations.region'),
        ),
        migrations.AddField(
            model_name='attractionimage',
            name='attraction',
            field=models.ForeignKey(help_text='The attraction this image belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='images', to='destinations.attraction'),
        ),
        migrations.AddField(
            model_name='attraction',
            name='destination',
            field=models.ForeignKey(help_text='The destination this attraction belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='attractions', to='destinations.destination'),
        ),
        migrations.AlterUniqueTogether(
            name='season',
            unique_together={('destination', 'name')},
        ),
        migrations.AddIndex(
            model_name='destination',
            index=models.Index(fields=['name'], name='destination_name_96ccc3_idx'),
        ),
        migrations.AddIndex(
            model_name='destination',
            index=models.Index(fields=['is_featured'], name='destination_is_feat_54f559_idx'),
        ),
        migrations.AddIndex(
            model_name='destination',
            index=models.Index(fields=['is_active'], name='destination_is_acti_09f11c_idx'),
        ),
    ]
