# Generated by Django 5.2.3 on 2025-08-01 06:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('destinations', '0002_attractionimage'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='destination',
            name='approval_status',
            field=models.CharField(choices=[('PENDING', 'Pending Approval'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', help_text='Current review status of this destination', max_length=20),
        ),
        migrations.AddField(
            model_name='destination',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='User who created this destination', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_destinations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='destination',
            name='rejection_reason',
            field=models.TextField(blank=True, help_text='Reason for rejection, if applicable', null=True),
        ),
        migrations.AddField(
            model_name='destination',
            name='review_date',
            field=models.DateTimeField(blank=True, help_text='When this destination was reviewed', null=True),
        ),
        migrations.AddField(
            model_name='destination',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, help_text='Manager or admin who reviewed this destination', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_destinations', to=settings.AUTH_USER_MODEL),
        ),
    ]
