# Generated by Django 5.2.3 on 2025-08-01 06:53

from django.db import migrations, models
import django.db.models.deletion
from django.conf import settings

class Migration(migrations.Migration):

    dependencies = [
        ('destinations', '0003_destination_approval_status_destination_created_by_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='destination',
            name='approval_status',
            field=models.CharField(
                choices=[('PENDING', 'Pending Approval'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')],
                default='PENDING',
                help_text='Current review status of this destination',
                max_length=20
            ),
        ),
    ]
