# Generated by Django 5.2.3 on 2025-08-03 06:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('destinations', '0004_add_approval_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PendingDestination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=120, unique=True)),
                ('short_description', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('country', models.CharField(blank=True, max_length=100, null=True)),
                ('approval_status', models.CharField(choices=[('PENDING', 'Pending Approval'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', help_text='Current review status of this pending destination', max_length=20)),
                ('review_date', models.DateTimeField(blank=True, help_text='When this destination was reviewed', null=True)),
                ('rejection_reason', models.TextField(blank=True, help_text='Reason for rejection, if applicable', null=True)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, help_text='Local guide who submitted this destination', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pending_destinations', to=settings.AUTH_USER_MODEL)),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pending_destinations', to='destinations.region')),
                ('reviewed_by', models.ForeignKey(blank=True, help_text='Manager or admin who reviewed this destination', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_pending_destinations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Pending Destination',
                'verbose_name_plural': 'Pending Destinations',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PendingDestinationImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='pending_destinations/')),
                ('caption', models.CharField(blank=True, max_length=255, null=True)),
                ('is_primary', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('pending_destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='destinations.pendingdestination')),
            ],
            options={
                'verbose_name': 'Pending Destination Image',
                'verbose_name_plural': 'Pending Destination Images',
                'ordering': ['-is_primary', 'created_at'],
            },
        ),
    ]
