# Generated by Django 5.2.3 on 2025-06-30 14:14

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('destinations', '__first__'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TourCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the category', max_length=100, unique=True)),
                ('slug', models.SlugField(help_text='URL-friendly version of the name', max_length=100, unique=True)),
                ('description', models.TextField(blank=True, help_text='Description of the category')),
                ('icon', models.CharField(blank=True, help_text='Font Awesome icon class', max_length=50)),
                ('is_active', models.BooleanField(default=True, help_text='Whether the category is active')),
            ],
            options={
                'verbose_name': 'Tour Category',
                'verbose_name_plural': 'Tour Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Tour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Title of the tour', max_length=200)),
                ('slug', models.SlugField(help_text='URL-friendly version of the title', max_length=200, unique=True)),
                ('short_description', models.CharField(blank=True, help_text='Brief description for listings', max_length=255)),
                ('description', models.TextField(help_text='Detailed description of the tour')),
                ('duration_days', models.PositiveIntegerField(help_text='Duration in days')),
                ('duration_nights', models.PositiveIntegerField(help_text='Duration in nights')),
                ('max_group_size', models.PositiveIntegerField(default=10, help_text='Maximum group size')),
                ('difficulty', models.CharField(choices=[('easy', 'Easy'), ('moderate', 'Moderate'), ('challenging', 'Challenging'), ('difficult', 'Difficult')], default='moderate', help_text='Difficulty level of the tour', max_length=20)),
                ('price', models.DecimalField(decimal_places=2, help_text='Base price of the tour', max_digits=10)),
                ('discount_price', models.DecimalField(blank=True, decimal_places=2, help_text='Discounted price if any', max_digits=10, null=True)),
                ('is_featured', models.BooleanField(default=False, help_text='Whether the tour is featured')),
                ('is_active', models.BooleanField(default=True, help_text='Whether the tour is active and bookable')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When the tour was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When the tour was last updated')),
                ('destination', models.ForeignKey(help_text='The destination this tour is for', on_delete=django.db.models.deletion.CASCADE, related_name='tours', to='destinations.destination')),
                ('category', models.ForeignKey(blank=True, help_text='Category of the tour', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tours', to='tours.tourcategory')),
            ],
            options={
                'ordering': ['-is_featured', 'title'],
            },
        ),
        migrations.CreateModel(
            name='TourDate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(help_text='Start date of the tour')),
                ('end_date', models.DateField(help_text='End date of the tour')),
                ('price', models.DecimalField(blank=True, decimal_places=2, help_text='Price for this specific date (overrides tour.price if set)', max_digits=10, null=True)),
                ('available_spots', models.PositiveIntegerField(default=0, help_text='Number of spots available for this date')),
                ('is_guaranteed', models.BooleanField(default=False, help_text='Whether the departure is guaranteed')),
                ('notes', models.TextField(blank=True, help_text='Additional notes about this specific tour date')),
                ('tour', models.ForeignKey(help_text='The tour these dates are for', on_delete=django.db.models.deletion.CASCADE, related_name='dates', to='tours.tour')),
            ],
            options={
                'verbose_name': 'Tour Date',
                'verbose_name_plural': 'Tour Dates',
                'ordering': ['start_date'],
            },
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_of_people', models.PositiveIntegerField(default=1, help_text='Number of people included in the booking')),
                ('booking_date', models.DateTimeField(auto_now_add=True, help_text='When the booking was made')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('cancelled', 'Cancelled'), ('completed', 'Completed')], default='pending', help_text='Current status of the booking', max_length=20)),
                ('total_amount', models.DecimalField(decimal_places=2, help_text='Total amount for the booking', max_digits=10)),
                ('payment_status', models.CharField(choices=[('pending', 'Pending'), ('partially_paid', 'Partially Paid'), ('paid', 'Paid'), ('refunded', 'Refunded')], default='pending', help_text='Current status of the payment', max_length=20)),
                ('special_requests', models.TextField(blank=True, help_text='Any special requests from the user')),
                ('contact_email', models.EmailField(help_text='Contact email for the booking', max_length=254)),
                ('contact_phone', models.CharField(blank=True, help_text='Contact phone for the booking', max_length=20)),
                ('user', models.ForeignKey(help_text='The user making the booking', on_delete=django.db.models.deletion.CASCADE, related_name='tour_bookings', to=settings.AUTH_USER_MODEL)),
                ('tour', models.ForeignKey(help_text='The tour being booked', on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='tours.tour')),
                ('tour_date', models.ForeignKey(help_text='The specific date of the tour being booked', on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='tours.tourdate')),
            ],
            options={
                'verbose_name': 'Tour Booking',
                'verbose_name_plural': 'Tour Bookings',
                'ordering': ['-booking_date'],
            },
        ),
        migrations.CreateModel(
            name='TourImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(help_text='The image file', upload_to='tours/')),
                ('caption', models.CharField(blank=True, help_text='Optional caption for the image', max_length=255)),
                ('is_primary', models.BooleanField(default=False, help_text='Whether this is the primary image for the tour')),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order for the image')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When the image was uploaded')),
                ('tour', models.ForeignKey(help_text='The tour this image belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='images', to='tours.tour')),
            ],
            options={
                'verbose_name': 'Tour Image',
                'verbose_name_plural': 'Tour Images',
                'ordering': ['order', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='TourInclusion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the inclusion', max_length=200)),
                ('description', models.TextField(blank=True, help_text='Description of the inclusion')),
                ('is_included', models.BooleanField(default=True, help_text='Whether this is included or excluded')),
                ('tour', models.ForeignKey(help_text='The tour this inclusion belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='inclusions', to='tours.tour')),
            ],
            options={
                'ordering': ['-is_included', 'name'],
            },
        ),
        migrations.CreateModel(
            name='TourItinerary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_number', models.PositiveIntegerField(help_text='The day number of the itinerary')),
                ('title', models.CharField(help_text="Title for this day's activities", max_length=200)),
                ('description', models.TextField(help_text="Detailed description of the day's activities")),
                ('accommodation', models.CharField(blank=True, help_text='Information about the accommodation for this day', max_length=255)),
                ('meals', models.CharField(blank=True, help_text='Information about meals included on this day', max_length=255)),
                ('tour', models.ForeignKey(help_text='The tour this itinerary belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='itineraries', to='tours.tour')),
            ],
            options={
                'verbose_name_plural': 'Tour Itineraries',
                'ordering': ['tour', 'day_number'],
            },
        ),
        migrations.CreateModel(
            name='TourReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveSmallIntegerField(help_text='Rating from 1 to 5 stars', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('comment', models.TextField(help_text='The review text')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When the review was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When the review was last updated')),
                ('is_approved', models.BooleanField(default=False, help_text='Whether the review has been approved for display')),
                ('tour', models.ForeignKey(help_text='The tour being reviewed', on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='tours.tour')),
                ('user', models.ForeignKey(help_text='The user who wrote the review', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tour_reviews', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='tour',
            index=models.Index(fields=['title'], name='tours_tour_title_b84fca_idx'),
        ),
        migrations.AddIndex(
            model_name='tour',
            index=models.Index(fields=['is_featured'], name='tours_tour_is_feat_bdd21d_idx'),
        ),
        migrations.AddIndex(
            model_name='tour',
            index=models.Index(fields=['is_active'], name='tours_tour_is_acti_e79caf_idx'),
        ),
        migrations.AddIndex(
            model_name='tour',
            index=models.Index(fields=['price'], name='tours_tour_price_674fc5_idx'),
        ),
        migrations.AddIndex(
            model_name='tourdate',
            index=models.Index(fields=['start_date'], name='tours_tourd_start_d_7fae9b_idx'),
        ),
        migrations.AddIndex(
            model_name='tourdate',
            index=models.Index(fields=['is_guaranteed'], name='tours_tourd_is_guar_be221c_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='tourdate',
            unique_together={('tour', 'start_date')},
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['status'], name='tours_booki_status_7604a9_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['payment_status'], name='tours_booki_payment_6adbc6_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['booking_date'], name='tours_booki_booking_0c1ca7_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='touritinerary',
            unique_together={('tour', 'day_number')},
        ),
        migrations.AlterUniqueTogether(
            name='tourreview',
            unique_together={('tour', 'user')},
        ),
    ]
