"""
Models for the itineraries application.

This file contains database models for creating and managing travel itineraries,
including day-by-day schedules, activities, and related metadata.
"""

from django.db import models
from django.utils.translation import gettext_lazy as _
from django.utils import timezone
from django.conf import settings
from destinations.models import Destination
from tours.models import Tour


class Itinerary(models.Model):
    """
    Main itinerary model representing a complete travel plan.
    
    This model stores the overall itinerary information including title,
    description, start and end dates, and relations to destinations.
    """
    title = models.CharField(
        _("Title"), 
        max_length=255,
        help_text=_("Name of the itinerary")
    )
    description = models.TextField(
        _("Description"), 
        help_text=_("Detailed description of the overall itinerary")
    )
    user = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.CASCADE,
        related_name='itineraries',
        help_text=_("User who created this itinerary")
    )
    tour = models.ForeignKey(
        Tour,
        on_delete=models.SET_NULL,
        null=True,
        blank=True,
        related_name='itineraries',
        help_text=_("Associated tour package, if applicable")
    )
    start_date = models.DateField(
        _("Start Date"),
        help_text=_("When the itinerary begins")
    )
    end_date = models.DateField(
        _("End Date"),
        help_text=_("When the itinerary ends")
    )
    is_public = models.BooleanField(
        _("Public"),
        default=False,
        help_text=_("Whether this itinerary is visible to other users")
    )
    is_ai_generated = models.BooleanField(
        _("AI Generated"),
        default=False,
        help_text=_("Whether this itinerary was generated by AI")
    )
    ai_provider = models.CharField(
        _("AI Provider"),
        max_length=20,
        choices=[
            ('openai', 'OpenAI'),
            ('gemini', 'Google Gemini'),
        ],
        null=True,
        blank=True,
        help_text=_("Which AI provider was used to generate this itinerary")
    )
    created_at = models.DateTimeField(
        _("Created At"),
        default=timezone.now,
        help_text=_("When this itinerary was created")
    )
    updated_at = models.DateTimeField(
        _("Updated At"),
        auto_now=True,
        help_text=_("When this itinerary was last updated")
    )
    
    class Meta:
        verbose_name = _("Itinerary")
        verbose_name_plural = _("Itineraries")
        ordering = ['-start_date']
    
    def __str__(self):
        """
        Return a string representation of this itinerary.
        
        Returns:
            str: The itinerary title
        """
        return self.title
    
    def get_duration(self):
        """
        Calculate the duration of the itinerary in days.
        
        Returns:
            int: Number of days the itinerary spans
        """
        delta = self.end_date - self.start_date
        return delta.days + 1  # Include the end date


class ItineraryDay(models.Model):
    """
    Represents a single day in an itinerary.
    
    Each day contains multiple activities and information about
    accommodations and transportation.
    """
    itinerary = models.ForeignKey(
        Itinerary,
        on_delete=models.CASCADE,
        related_name='days',
        help_text=_("The parent itinerary this day belongs to")
    )
    day_number = models.PositiveSmallIntegerField(
        _("Day Number"),
        help_text=_("Which day in the itinerary (1-based)")
    )
    date = models.DateField(
        _("Date"),
        help_text=_("Calendar date for this itinerary day")
    )
    destination = models.ForeignKey(
        Destination,
        on_delete=models.SET_NULL,
        null=True,
        blank=True,
        related_name='itinerary_days',
        help_text=_("Main destination visited on this day")
    )
    accommodation_details = models.TextField(
        _("Accommodation Details"),
        blank=True,
        help_text=_("Details about where to stay on this night")
    )
    notes = models.TextField(
        _("Notes"),
        blank=True,
        help_text=_("Additional notes for this day")
    )
    
    class Meta:
        verbose_name = _("Itinerary Day")
        verbose_name_plural = _("Itinerary Days")
        ordering = ['itinerary', 'day_number']
        unique_together = [['itinerary', 'day_number']]
    
    def __str__(self):
        """
        Return a string representation of this itinerary day.
        
        Returns:
            str: Description of the day including itinerary title and day number
        """
        return f"{self.itinerary.title} - Day {self.day_number}"


class Activity(models.Model):
    """
    Represents a specific activity within an itinerary day.
    
    Activities are scheduled events with start/end times, locations, and descriptions.
    """
    day = models.ForeignKey(
        ItineraryDay,
        on_delete=models.CASCADE,
        related_name='activities',
        help_text=_("The day this activity belongs to")
    )
    title = models.CharField(
        _("Title"),
        max_length=255,
        help_text=_("Name of the activity")
    )
    description = models.TextField(
        _("Description"),
        blank=True,
        help_text=_("Detailed description of the activity")
    )
    start_time = models.TimeField(
        _("Start Time"),
        help_text=_("When the activity begins")
    )
    end_time = models.TimeField(
        _("End Time"),
        help_text=_("When the activity ends")
    )
    location = models.CharField(
        _("Location"),
        max_length=255,
        blank=True,
        help_text=_("Where the activity takes place")
    )
    cost = models.DecimalField(
        _("Cost"),
        max_digits=10,
        decimal_places=2,
        null=True,
        blank=True,
        help_text=_("Cost of the activity (if applicable)")
    )
    booking_reference = models.CharField(
        _("Booking Reference"),
        max_length=100,
        blank=True,
        help_text=_("Reference number for any bookings")
    )
    
    class Meta:
        verbose_name = _("Activity")
        verbose_name_plural = _("Activities")
        ordering = ['day', 'start_time']
    
    def __str__(self):
        """
        Return a string representation of this activity.
        
        Returns:
            str: The activity title
        """
        return self.title
    
    def get_duration_minutes(self):
        """
        Calculate the duration of the activity in minutes.
        
        Returns:
            int: Duration in minutes
        """
        if not all([self.start_time, self.end_time]):
            return 0
            
        start_minutes = self.start_time.hour * 60 + self.start_time.minute
        end_minutes = self.end_time.hour * 60 + self.end_time.minute
        return max(0, end_minutes - start_minutes)
