# Generated by Django 5.2.8 on 2025-11-22 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivery_method',
            field=models.CharField(choices=[('delivery', 'Delivery'), ('takeaway', 'Takeaway')], default='delivery', max_length=20),
        ),
        migrations.AlterField(
            model_name='order',
            name='customer_address',
            field=models.TextField(blank=True, null=True),
        ),
    ]
