# Generated by Django 5.2.8 on 2025-11-24 16:52

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_order_user'),
        ('restaurant', '0004_managerloginlog'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivery_charge',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Delivery charge for this order', max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='order',
            name='discount_amount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Total discount amount applied to this order', max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='order',
            name='free_delivery_applied',
            field=models.BooleanField(default=False, help_text='Whether free delivery was applied via promo code'),
        ),
        migrations.CreateModel(
            name='PromoCode',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(help_text='Unique promo code that customers will enter', max_length=20, unique=True)),
                ('name', models.CharField(help_text='Display name for the promo code', max_length=100)),
                ('description', models.TextField(blank=True, help_text='Description of the promo code for customers')),
                ('discount_type', models.CharField(choices=[('percentage', 'Percentage Off'), ('fixed', 'Fixed Amount Off'), ('free_delivery', 'Free Delivery')], help_text='Type of discount to apply', max_length=20)),
                ('discount_value', models.DecimalField(decimal_places=2, help_text='Discount value (percentage or amount)', max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('minimum_order_amount', models.DecimalField(decimal_places=2, default=0, help_text='Minimum order amount required to use this promo code', max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('max_discount_amount', models.DecimalField(blank=True, decimal_places=2, help_text='Maximum discount amount for percentage discounts', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('usage_limit', models.PositiveIntegerField(blank=True, help_text='Maximum number of times this promo code can be used', null=True)),
                ('usage_limit_per_user', models.PositiveIntegerField(blank=True, help_text='Maximum times a single user can use this promo code', null=True)),
                ('start_date', models.DateTimeField(help_text='When the promo code becomes active')),
                ('end_date', models.DateTimeField(help_text='When the promo code expires')),
                ('first_time_only', models.BooleanField(default=False, help_text='Only for first-time customers')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this promo code is currently active')),
                ('times_used', models.PositiveIntegerField(default=0, help_text='Total number of times this promo code has been used')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('restaurant', models.ForeignKey(blank=True, help_text='Restaurant this promo code belongs to (null for global codes)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='promo_codes', to='restaurant.restaurant')),
            ],
            options={
                'verbose_name': 'Promo Code',
                'verbose_name_plural': 'Promo Codes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='order',
            name='promo_code',
            field=models.ForeignKey(blank=True, help_text='Promo code applied to this order', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='orders.promocode'),
        ),
        migrations.CreateModel(
            name='PromoCodeUsage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('discount_amount', models.DecimalField(decimal_places=2, help_text='Amount of discount applied', max_digits=10)),
                ('free_delivery_applied', models.BooleanField(default=False, help_text='Whether free delivery was applied')),
                ('used_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promo_code_usage', to='orders.order')),
                ('promo_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usages', to='orders.promocode')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promo_code_usages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Promo Code Usage',
                'verbose_name_plural': 'Promo Code Usages',
                'ordering': ['-used_at'],
            },
        ),
        migrations.CreateModel(
            name='SeasonalPromotion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('promotion_type', models.CharField(choices=[('seasonal', 'Seasonal Promotion'), ('flash_sale', 'Flash Sale'), ('holiday', 'Holiday Special'), ('event', 'Special Event')], max_length=20)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('auto_generate_codes', models.BooleanField(default=True, help_text='Automatically generate promo codes for this promotion')),
                ('code_prefix', models.CharField(help_text='Prefix for auto-generated promo codes', max_length=10)),
                ('discount_type', models.CharField(choices=[('percentage', 'Percentage Off'), ('fixed', 'Fixed Amount Off'), ('free_delivery', 'Free Delivery')], max_length=20)),
                ('discount_value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('minimum_order_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('usage_limit_per_code', models.PositiveIntegerField(default=100)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('restaurants', models.ManyToManyField(blank=True, help_text='Restaurants included in this promotion (empty = all restaurants)', to='restaurant.restaurant')),
            ],
            options={
                'verbose_name': 'Seasonal Promotion',
                'verbose_name_plural': 'Seasonal Promotions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='promocode',
            index=models.Index(fields=['code'], name='orders_prom_code_04587b_idx'),
        ),
        migrations.AddIndex(
            model_name='promocode',
            index=models.Index(fields=['restaurant', 'is_active'], name='orders_prom_restaur_e0fd25_idx'),
        ),
        migrations.AddIndex(
            model_name='promocode',
            index=models.Index(fields=['start_date', 'end_date'], name='orders_prom_start_d_c54a66_idx'),
        ),
        migrations.AddIndex(
            model_name='promocodeusage',
            index=models.Index(fields=['promo_code', 'user'], name='orders_prom_promo_c_273a5b_idx'),
        ),
        migrations.AddIndex(
            model_name='promocodeusage',
            index=models.Index(fields=['used_at'], name='orders_prom_used_at_427160_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='promocodeusage',
            unique_together={('user', 'order')},
        ),
    ]
