# Generated by Django 5.2.8 on 2025-11-30 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_order_delivery_charge_order_discount_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivery_time',
            field=models.CharField(choices=[('asap', 'ASAP (25-35 min)'), ('30min', '30 minutes'), ('1hr', '1 hour'), ('2hr', '2 hours')], default='asap', help_text='Preferred delivery time slot selected by customer', max_length=10),
        ),
    ]
