# Generated by Django 5.2.8 on 2025-12-02 18:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_order_payment_method_order_payment_status_and_more'),
        ('restaurant', '0007_restauranttable'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='is_table_order',
            field=models.BooleanField(default=False, help_text='Quick flag to identify table-based orders (QR code or dine-in)'),
        ),
        migrations.AddField(
            model_name='order',
            name='order_type',
            field=models.CharField(choices=[('qr_code', 'QR Code Order'), ('dine_in', 'Dine In'), ('delivery', 'Delivery'), ('takeaway', 'Takeaway'), ('staff', 'Staff Order')], default='delivery', help_text='Type of order: QR code, dine-in, delivery, takeaway, or staff order', max_length=20),
        ),
        migrations.AddField(
            model_name='order',
            name='table',
            field=models.ForeignKey(blank=True, help_text='Table from which this order was placed (for QR code and dine-in orders)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='restaurant.restauranttable'),
        ),
        migrations.AlterField(
            model_name='order',
            name='delivery_method',
            field=models.CharField(choices=[('delivery', 'Delivery'), ('takeaway', 'Takeaway'), ('dine_in', 'Dine In')], default='delivery', max_length=20),
        ),
    ]
