# Generated by Django 5.2.8 on 2025-12-03 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_order_is_table_order_order_order_type_order_table_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='guest_email',
            field=models.EmailField(blank=True, help_text='Guest email for bill delivery (QR table orders)', max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='guest_phone',
            field=models.CharField(blank=True, help_text='Guest phone for bill delivery (QR table orders)', max_length=15, null=True),
        ),
    ]
