# Generated by Django 5.2.3 on 2025-08-02 10:28

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField(verbose_name='Object ID')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('content', models.TextField(verbose_name='Content')),
                ('rating', models.IntegerField(choices=[(1, '★☆☆☆☆'), (2, '★★☆☆☆'), (3, '★★★☆☆'), (4, '★★★★☆'), (5, '★★★★★')], verbose_name='Rating')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20, verbose_name='Status')),
                ('featured', models.BooleanField(default=False, verbose_name='Featured')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype', verbose_name='Content Type')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Review',
                'verbose_name_plural': 'Reviews',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReviewComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(help_text='Enter your comment here', verbose_name='Content')),
                ('is_official_response', models.BooleanField(default=False, help_text='Check if this is an official response from staff', verbose_name='Official Response')),
                ('is_approved', models.BooleanField(default=True, help_text='Whether this comment has been approved by moderators', verbose_name='Approved')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('parent', models.ForeignKey(blank=True, help_text='Parent comment if this is a reply', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='reviews.reviewcomment', verbose_name='Parent Comment')),
                ('review', models.ForeignKey(help_text='The review this comment belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='reviews.review', verbose_name='Review')),
                ('user', models.ForeignKey(help_text='The user who created this comment', on_delete=django.db.models.deletion.CASCADE, related_name='review_comments', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Review Comment',
                'verbose_name_plural': 'Review Comments',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReviewHelpful',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vote_type', models.CharField(choices=[('helpful', 'Helpful'), ('not_helpful', 'Not Helpful')], default='helpful', help_text='Type of vote cast', max_length=20, verbose_name='Vote Type')),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='IP address of the voter', null=True, verbose_name='IP Address')),
                ('user_agent', models.TextField(blank=True, help_text='Browser/device information', null=True, verbose_name='User Agent')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, help_text='When this vote was cast', verbose_name='Created At')),
                ('review', models.ForeignKey(help_text='The review that was voted on', on_delete=django.db.models.deletion.CASCADE, related_name='helpful_records', to='reviews.review', verbose_name='Review')),
                ('user', models.ForeignKey(help_text='User who cast the vote', on_delete=django.db.models.deletion.CASCADE, related_name='helpful_votes', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Helpful Vote',
                'verbose_name_plural': 'Helpful Votes',
                'unique_together': {('review', 'user')},
            },
        ),
        migrations.AddField(
            model_name='review',
            name='helpful_votes',
            field=models.ManyToManyField(help_text='Users who marked this review as helpful', related_name='helpful_reviews', through='reviews.ReviewHelpful', to=settings.AUTH_USER_MODEL, verbose_name='Helpful Votes'),
        ),
        migrations.CreateModel(
            name='ReviewImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(help_text='Upload an image to include with your review', upload_to='reviews/%Y/%m/', verbose_name='Image')),
                ('caption', models.CharField(blank=True, help_text='Optional description for this image', max_length=255, verbose_name='Caption')),
                ('is_primary', models.BooleanField(default=False, help_text='Set as the main image for this review', verbose_name='Primary Image')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('review', models.ForeignKey(help_text='The review this image belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='images', to='reviews.review', verbose_name='Review')),
            ],
            options={
                'verbose_name': 'Review Image',
                'verbose_name_plural': 'Review Images',
                'ordering': ['created_at'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='review',
            unique_together={('user', 'content_type', 'object_id')},
        ),
    ]
