# Generated by Django 5.2.3 on 2025-07-28 18:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userprofile',
            options={},
        ),
        migrations.CreateModel(
            name='GuideApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('application_date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending Review'), ('UNDER_REVIEW', 'Under Review'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20)),
                ('government_id', models.FileField(help_text='Upload your government-issued ID proof', upload_to='guide_applications/ids/')),
                ('id_type', models.CharField(help_text='Type of ID provided (e.g., Aadhaar, PAN, Passport)', max_length=100)),
                ('experience', models.TextField(help_text='Describe your experience as a local guide')),
                ('areas_of_expertise', models.TextField(help_text='List the areas/regions you have expertise in')),
                ('languages', models.JSONField(default=list, help_text='List of languages you speak')),
                ('review_date', models.DateTimeField(blank=True, null=True)),
                ('review_notes', models.TextField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True, null=True)),
                ('id_verification_status', models.BooleanField(default=False, help_text='ID verified by admin')),
                ('background_check_status', models.BooleanField(default=False, help_text='Background check completed')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_applications', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guide_applications', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='VerificationToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=100, unique=True)),
                ('token_type', models.CharField(choices=[('email_verification', 'Email Verification'), ('password_reset', 'Password Reset'), ('account_recovery', 'Account Recovery')], default='email_verification', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('is_used', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verification_tokens', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Verification Token',
                'verbose_name_plural': 'Verification Tokens',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['token'], name='accounts_ve_token_e31831_idx'), models.Index(fields=['user', 'token_type', 'is_used'], name='accounts_ve_user_id_21e434_idx'), models.Index(fields=['expires_at'], name='accounts_ve_expires_1a25b4_idx')],
            },
        ),
    ]
