# Generated by Django 5.2.3 on 2025-08-03 17:27

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_userprofile_options_guideapplication_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='guideapplication',
            options={'ordering': ['-application_date'], 'permissions': [('can_review_applications', 'Can review guide applications'), ('can_verify_ids', 'Can verify government IDs')], 'verbose_name': 'Guide Application', 'verbose_name_plural': 'Guide Applications'},
        ),
        migrations.AddField(
            model_name='guideapplication',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='guideapplication',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='guideapplication',
            name='application_date',
            field=models.DateTimeField(auto_now_add=True, help_text='Date and time when the application was submitted'),
        ),
        migrations.AlterField(
            model_name='guideapplication',
            name='areas_of_expertise',
            field=models.TextField(help_text='List the cities, regions, or types of locations you have expertise in'),
        ),
        migrations.AlterField(
            model_name='guideapplication',
            name='background_check_status',
            field=models.BooleanField(default=False, help_text='Indicates if background check has been completed'),
        ),
        migrations.AlterField(
            model_name='guideapplication',
            name='experience',
            field=models.TextField(help_text='Describe your experience as a local guide or in the tourism industry'),
        ),
        migrations.AlterField(
            model_name='guideapplication',
            name='government_id',
            field=models.FileField(help_text='Scanned copy of government-issued ID proof', upload_to='guide_applications/ids/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='guideapplication',
            name='id_type',
            field=models.CharField(help_text="Type of ID provided (e.g., Aadhaar, PAN, Passport, Driver's License)", max_length=100),
        ),
        migrations.AlterField(
            model_name='guideapplication',
            name='id_verification_status',
            field=models.BooleanField(default=False, help_text='Indicates if the ID has been verified by an admin'),
        ),
        migrations.AlterField(
            model_name='guideapplication',
            name='languages',
            field=models.JSONField(default=list, help_text='List of languages you are fluent in (format: [{"language": "English", "proficiency": "Native"}])'),
        ),
        migrations.AlterField(
            model_name='guideapplication',
            name='rejection_reason',
            field=models.TextField(blank=True, help_text='Reason provided if the application was rejected', null=True),
        ),
        migrations.AlterField(
            model_name='guideapplication',
            name='review_date',
            field=models.DateTimeField(blank=True, help_text='Date and time when the application was reviewed', null=True),
        ),
        migrations.AlterField(
            model_name='guideapplication',
            name='review_notes',
            field=models.TextField(blank=True, help_text='Internal notes about the application review', null=True),
        ),
        migrations.AlterField(
            model_name='guideapplication',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, help_text='Admin/Manager who reviewed the application', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_applications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='guideapplication',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending Review'), ('UNDER_REVIEW', 'Under Review'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', help_text='Current status of the application', max_length=20),
        ),
        migrations.AlterField(
            model_name='guideapplication',
            name='user',
            field=models.ForeignKey(help_text='User who submitted the application', on_delete=django.db.models.deletion.CASCADE, related_name='guide_applications', to=settings.AUTH_USER_MODEL),
        ),
    ]
