"""
Migration to add AI-related fields to Itinerary model.

This migration adds two new fields:
1. is_ai_generated - Boolean to track if the itinerary was AI-generated
2. ai_provider - CharField to track which AI provider was used
"""

from django.db import migrations, models


def add_ai_fields(apps, schema_editor):
    """
    Add the AI-related fields to the Itinerary model.
    
    Args:
        apps: Registry of installed applications
        schema_editor: For database schema manipulation
    """
    Itinerary = apps.get_model('itineraries', 'Itinerary')
    
    # Add is_ai_generated field
    is_ai_generated = models.BooleanField(
        default=False,
        help_text="Whether this itinerary was generated by AI"
    )
    is_ai_generated.contribute_to_class(Itinerary, 'is_ai_generated')
    
    # Add ai_provider field
    ai_provider = models.CharField(
        max_length=20,
        choices=[
            ('openai', 'OpenAI'),
            ('gemini', 'Google Gemini'),
        ],
        null=True,
        blank=True,
        help_text="Which AI provider was used to generate this itinerary"
    )
    ai_provider.contribute_to_class(Itinerary, 'ai_provider')
    
    # Create a temporary model to represent the current state
    temp_model = apps.get_model('itineraries', 'Itinerary')
    
    # Create the fields in the database
    schema_editor.add_field(
        temp_model,
        temp_model._meta.get_field('is_ai_generated')
    )
    schema_editor.add_field(
        temp_model,
        temp_model._meta.get_field('ai_provider')
    )


def remove_ai_fields(apps, schema_editor):
    """
    Remove the AI-related fields from the Itinerary model.
    
    Args:
        apps: Registry of installed applications
        schema_editor: For database schema manipulation
    """
    Itinerary = apps.get_model('itineraries', 'Itinerary')
    
    # Remove the fields from the model
    schema_editor.remove_field(Itinerary, 'is_ai_generated')
    schema_editor.remove_field(Itinerary, 'ai_provider')


class Migration(migrations.Migration):
    """
    Migration class for adding AI-related fields to Itinerary model.
    """
    
    dependencies = [
        ('itineraries', '0011_add_ai_provider_to_itinerary'),
    ]
    
    operations = [
        migrations.RunPython(
            code=add_ai_fields,
            reverse_code=remove_ai_fields,
            atomic=True
        ),
    ]
