"""
Migration to add AI-related fields to Itinerary model.

This migration adds two fields:
1. is_ai_generated - Boolean to track if the itinerary was AI-generated
2. ai_provider - CharField to track which AI provider was used (OpenAI/Gemini)
"""

from django.db import migrations, models


class Migration(migrations.Migration):
    """
    Migration class for adding AI-related fields to Itinerary model.
    """
    
    dependencies = [
        ('itineraries', '0011_add_ai_provider_to_itinerary'),
    ]
    
    operations = [
        migrations.AddField(
            model_name='itinerary',
            name='is_ai_generated',
            field=models.BooleanField(
                default=False,
                help_text='Whether this itinerary was generated by AI',
                verbose_name='AI Generated'
            ),
        ),
        migrations.AddField(
            model_name='itinerary',
            name='ai_provider',
            field=models.CharField(
                blank=True,
                choices=[('openai', 'OpenAI'), ('gemini', 'Google Gemini')],
                help_text='Which AI provider was used to generate this itinerary',
                max_length=20,
                null=True,
                verbose_name='AI Provider'
            ),
        ),
    ]
