# Generated by Django 5.2.3 on 2025-07-24 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='securitylog',
            name='event_type',
            field=models.CharField(choices=[('LOGIN', 'User Login'), ('LOGOUT', 'User Logout'), ('LOGIN_FAIL', 'Failed Login Attempt'), ('PASSWORD_CHANGE', 'Password Changed'), ('PASSWORD_RESET', 'Password Reset'), ('USER_CREATED', 'User Account Created'), ('USER_DELETED', 'User Account Deleted'), ('PERMISSION_CHANGE', 'Permission Changed'), ('ADMIN_ACTION', 'Admin Action'), ('SECURITY_SCAN', 'Security Scan'), ('WAF_BLOCK', 'WAF Blocked Request'), ('2FA_ENABLED', '2FA Enabled'), ('2FA_DISABLED', '2FA Disabled'), ('2FA_CHALLENGE', '2FA Challenge'), ('LOGIN_BLOCKED', 'Login Blocked')], max_length=50),
        ),
    ]
