# Generated by Django 5.2.3 on 2025-07-29 17:07

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0002_alter_securitylog_event_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='securitylog',
            name='additional_data',
            field=models.JSONField(blank=True, help_text='Additional structured data related to the event in JSON format', null=True),
        ),
        migrations.AlterField(
            model_name='securitylog',
            name='description',
            field=models.TextField(help_text='Human-readable description of the security event'),
        ),
        migrations.AlterField(
            model_name='securitylog',
            name='event_type',
            field=models.CharField(choices=[('LOGIN', 'User Login'), ('LOGOUT', 'User Logout'), ('LOGIN_FAIL', 'Failed Login Attempt'), ('PASSWORD_CHANGE', 'Password Changed'), ('PASSWORD_RESET', 'Password Reset'), ('USER_CREATED', 'User Account Created'), ('USER_DELETED', 'User Account Deleted'), ('PERMISSION_CHANGE', 'Permission Changed'), ('ADMIN_ACTION', 'Admin Action'), ('SECURITY_SCAN', 'Security Scan'), ('WAF_BLOCK', 'WAF Blocked Request'), ('2FA_ENABLED', '2FA Enabled'), ('2FA_DISABLED', '2FA Disabled'), ('2FA_CHALLENGE', '2FA Challenge'), ('LOGIN_BLOCKED', 'Login Blocked')], help_text='Type of security event that occurred', max_length=50),
        ),
        migrations.AlterField(
            model_name='securitylog',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for the security log entry', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='securitylog',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, help_text='IP address from which the event originated', null=True),
        ),
        migrations.AlterField(
            model_name='securitylog',
            name='level',
            field=models.CharField(choices=[('INFO', 'Information'), ('WARNING', 'Warning'), ('ERROR', 'Error'), ('CRITICAL', 'Critical')], help_text='Severity level of the security event', max_length=10),
        ),
        migrations.AlterField(
            model_name='securitylog',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, db_index=True, help_text='When the security event occurred'),
        ),
        migrations.AlterField(
            model_name='securitylog',
            name='user',
            field=models.ForeignKey(blank=True, help_text='User associated with this security event, if applicable', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='securitylog',
            name='user_agent',
            field=models.TextField(blank=True, help_text='Browser/client user agent string', null=True),
        ),
    ]
