# Generated by Django 5.2.8 on 2025-11-22 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='cuisine_type',
            field=models.CharField(choices=[('italian', 'Italian'), ('indian', 'Indian'), ('american', 'American'), ('chinese', 'Chinese'), ('japanese', 'Japanese'), ('mexican', 'Mexican'), ('thai', 'Thai'), ('mediterranean', 'Mediterranean'), ('french', 'French'), ('other', 'Other')], default='other', help_text='Primary cuisine type of the restaurant', max_length=20),
        ),
    ]
