# Generated by Django 5.2.8 on 2025-11-22 08:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0002_restaurant_cuisine_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='approval_status',
            field=models.CharField(choices=[('pending', 'Pending Approval'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', help_text='Current approval status of the restaurant', max_length=20),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='is_approved',
            field=models.BooleanField(default=False, help_text='Whether the restaurant has been approved by a manager'),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='rejection_reason',
            field=models.TextField(blank=True, help_text='Reason for rejection if applicable', null=True),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='PendingRestaurant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('restaurant_name', models.CharField(help_text='Proposed restaurant name', max_length=200)),
                ('description', models.TextField(help_text='Restaurant description and specialties')),
                ('address', models.TextField(help_text='Restaurant physical address')),
                ('phone', models.CharField(help_text='Contact phone number', max_length=20)),
                ('email', models.EmailField(blank=True, help_text='Restaurant contact email', max_length=254, null=True)),
                ('cuisine_type', models.CharField(choices=[('italian', 'Italian'), ('indian', 'Indian'), ('american', 'American'), ('chinese', 'Chinese'), ('japanese', 'Japanese'), ('mexican', 'Mexican'), ('thai', 'Thai'), ('mediterranean', 'Mediterranean'), ('french', 'French'), ('other', 'Other')], default='other', help_text='Primary cuisine type', max_length=20)),
                ('image', models.ImageField(blank=True, help_text='Restaurant logo or cover photo', null=True, upload_to='pending_restaurants/')),
                ('opening_time', models.TimeField(default='09:00', help_text='Business opening time')),
                ('closing_time', models.TimeField(default='22:00', help_text='Business closing time')),
                ('minimum_order', models.DecimalField(decimal_places=2, default=0.0, help_text='Minimum order amount in rupees', max_digits=10)),
                ('delivery_fee', models.DecimalField(decimal_places=2, default=0.0, help_text='Delivery charge in rupees', max_digits=10)),
                ('status', models.CharField(choices=[('pending', 'Pending Approval'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', help_text='Application status', max_length=20)),
                ('rejection_reason', models.TextField(blank=True, help_text='Reason for rejection if applicable', null=True)),
                ('processed_at', models.DateTimeField(blank=True, help_text='When this application was processed', null=True)),
                ('processed_by', models.ForeignKey(blank=True, help_text='Manager who processed this application', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processed_restaurants', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(help_text='Customer applying to become a restaurant owner', on_delete=django.db.models.deletion.CASCADE, related_name='pending_restaurants', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Pending Restaurant',
                'verbose_name_plural': 'Pending Restaurants',
                'ordering': ['-created_at'],
            },
        ),
    ]
