# Generated by Django 5.2.8 on 2025-11-24 04:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0003_restaurant_approval_status_restaurant_is_approved_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ManagerLoginLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('login_time', models.DateTimeField(help_text='Timestamp when the manager logged in')),
                ('logout_time', models.DateTimeField(blank=True, help_text='Timestamp when the manager logged out', null=True)),
                ('ip_address', models.GenericIPAddressField(help_text='IP address from which the login originated')),
                ('user_agent', models.TextField(help_text='Browser and device information')),
                ('session_duration', models.PositiveIntegerField(blank=True, help_text='Session duration in minutes', null=True)),
                ('is_active_session', models.BooleanField(default=True, help_text='Whether this session is currently active')),
                ('user', models.ForeignKey(help_text='Staff member who performed the login', on_delete=django.db.models.deletion.CASCADE, related_name='manager_login_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Manager Login Log',
                'verbose_name_plural': 'Manager Login Logs',
                'ordering': ['-login_time'],
                'indexes': [models.Index(fields=['user', '-login_time'], name='restaurant__user_id_24eaa9_idx'), models.Index(fields=['-login_time'], name='restaurant__login_t_4c76b3_idx'), models.Index(fields=['is_active_session'], name='restaurant__is_acti_247f93_idx')],
            },
        ),
    ]
