# Generated by Django 5.2.8 on 2025-11-26 06:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0005_restaurant_image_url'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MarketingCampaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(help_text='Campaign name for internal reference', max_length=200)),
                ('subject', models.CharField(help_text='Email subject line for customers', max_length=200)),
                ('template', models.CharField(default='emails/promotional_base.html', help_text='Email template to use for this campaign', max_length=100)),
                ('message', models.TextField(help_text='Custom message content for the email')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('scheduled', 'Scheduled'), ('sending', 'Sending'), ('sent', 'Sent'), ('completed', 'Completed'), ('failed', 'Failed')], default='draft', help_text='Current status of the campaign', max_length=20)),
                ('target_customers', models.CharField(choices=[('all_customers', 'All Customers'), ('recent_customers', 'Recent Customers (Last 30 Days)'), ('repeat_customers', 'Repeat Customers (3+ Orders)'), ('high_value_customers', 'High Value Customers (Avg Order > ₹500)'), ('inactive_customers', 'Inactive Customers (No Orders in 60 Days)')], default='all_customers', help_text='Which customer segment to target', max_length=30)),
                ('scheduled_at', models.DateTimeField(blank=True, help_text='When to schedule the campaign for sending', null=True)),
                ('sent_at', models.DateTimeField(blank=True, help_text='When the campaign was actually sent', null=True)),
                ('created_by', models.ForeignKey(help_text='User who created this campaign', on_delete=django.db.models.deletion.CASCADE, related_name='created_campaigns', to=settings.AUTH_USER_MODEL)),
                ('restaurant', models.ForeignKey(help_text='Restaurant creating this campaign', on_delete=django.db.models.deletion.CASCADE, related_name='marketing_campaigns', to='restaurant.restaurant')),
            ],
            options={
                'verbose_name': 'Marketing Campaign',
                'verbose_name_plural': 'Marketing Campaigns',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CampaignRecipient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('email', models.EmailField(help_text='Email address used for sending', max_length=254)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('failed', 'Failed'), ('bounced', 'Bounced'), ('opened', 'Opened'), ('clicked', 'Clicked')], default='pending', help_text='Current delivery status', max_length=20)),
                ('sent_at', models.DateTimeField(blank=True, help_text='When the email was successfully sent', null=True)),
                ('error_message', models.TextField(blank=True, help_text='Error message if sending failed', null=True)),
                ('customer', models.ForeignKey(help_text='Customer who received the email', on_delete=django.db.models.deletion.CASCADE, related_name='campaign_recipients', to=settings.AUTH_USER_MODEL)),
                ('campaign', models.ForeignKey(help_text='Campaign this recipient belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='recipients', to='restaurant.marketingcampaign')),
            ],
            options={
                'verbose_name': 'Campaign Recipient',
                'verbose_name_plural': 'Campaign Recipients',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='marketingcampaign',
            index=models.Index(fields=['restaurant', '-created_at'], name='restaurant__restaur_11851c_idx'),
        ),
        migrations.AddIndex(
            model_name='marketingcampaign',
            index=models.Index(fields=['status'], name='restaurant__status_709f99_idx'),
        ),
        migrations.AddIndex(
            model_name='marketingcampaign',
            index=models.Index(fields=['scheduled_at'], name='restaurant__schedul_6d0e51_idx'),
        ),
        migrations.AddIndex(
            model_name='campaignrecipient',
            index=models.Index(fields=['campaign', 'status'], name='restaurant__campaig_35e6f2_idx'),
        ),
        migrations.AddIndex(
            model_name='campaignrecipient',
            index=models.Index(fields=['customer'], name='restaurant__custome_1c9a71_idx'),
        ),
        migrations.AddIndex(
            model_name='campaignrecipient',
            index=models.Index(fields=['status'], name='restaurant__status_fbc659_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='campaignrecipient',
            unique_together={('campaign', 'customer')},
        ),
    ]
