# Generated by Django 5.2.8 on 2025-12-02 17:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0006_marketingcampaign_campaignrecipient_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RestaurantTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('table_number', models.CharField(help_text='Table number or identifier (e.g., "T1", "A-5", "101")', max_length=20)),
                ('capacity', models.PositiveIntegerField(default=4, help_text='Number of people this table can accommodate')),
                ('qr_code', models.ImageField(blank=True, help_text='Generated QR code image for this table', null=True, upload_to='table_qr_codes/')),
                ('qr_code_uuid', models.UUIDField(help_text='Unique identifier for QR code URL', unique=True)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this table is currently active and available')),
                ('location_description', models.CharField(blank=True, help_text='Optional description of table location (e.g., "Near window", "Patio area")', max_length=200, null=True)),
                ('restaurant', models.ForeignKey(help_text='Restaurant that owns this table', on_delete=django.db.models.deletion.CASCADE, related_name='tables', to='restaurant.restaurant')),
            ],
            options={
                'verbose_name': 'Restaurant Table',
                'verbose_name_plural': 'Restaurant Tables',
                'ordering': ['restaurant', 'table_number'],
                'indexes': [models.Index(fields=['restaurant', 'table_number'], name='restaurant__restaur_6423f1_idx'), models.Index(fields=['qr_code_uuid'], name='restaurant__qr_code_0cc213_idx'), models.Index(fields=['is_active'], name='restaurant__is_acti_204436_idx')],
                'unique_together': {('restaurant', 'table_number')},
            },
        ),
    ]
