# Generated by Django 5.2.8 on 2025-12-03 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0007_restauranttable'),
    ]

    operations = [
        migrations.AddField(
            model_name='restauranttable',
            name='section',
            field=models.CharField(choices=[('ac', 'A/C'), ('non_ac', 'Non A/C'), ('bar', 'Bar')], default='ac', help_text='Restaurant section where this table is located', max_length=20),
        ),
    ]
