# Generated by Django 5.2.8 on 2025-12-07 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0008_restauranttable_section'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pendingrestaurant',
            name='address',
        ),
        migrations.RemoveField(
            model_name='pendingrestaurant',
            name='email',
        ),
        migrations.RemoveField(
            model_name='pendingrestaurant',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='restaurant',
            name='address',
        ),
        migrations.RemoveField(
            model_name='restaurant',
            name='email',
        ),
        migrations.RemoveField(
            model_name='restaurant',
            name='phone',
        ),
        migrations.AddField(
            model_name='pendingrestaurant',
            name='_address_encrypted',
            field=models.TextField(blank=True, help_text='Encrypted restaurant physical address', null=True),
        ),
        migrations.AddField(
            model_name='pendingrestaurant',
            name='_email_encrypted',
            field=models.TextField(blank=True, help_text='Encrypted restaurant contact email', null=True),
        ),
        migrations.AddField(
            model_name='pendingrestaurant',
            name='_phone_encrypted',
            field=models.TextField(blank=True, help_text='Encrypted contact phone number', null=True),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='_address_encrypted',
            field=models.TextField(blank=True, help_text='Encrypted restaurant physical address', null=True),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='_email_encrypted',
            field=models.TextField(blank=True, help_text='Encrypted restaurant contact email', null=True),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='_phone_encrypted',
            field=models.TextField(blank=True, help_text='Encrypted restaurant contact phone number', null=True),
        ),
    ]
