# Generated by Django 5.2.8 on 2025-12-07 09:03

from django.db import migrations


def encrypt_existing_restaurant_data(apps, schema_editor):
    """
    Encrypt existing plaintext restaurant and pending restaurant data.
    
    This function reads existing plaintext data from the old fields,
    encrypts it using the EncryptionManager, and stores it in the new encrypted fields.
    """
    from core.encryption import EncryptionManager
    
    Restaurant = apps.get_model('restaurant', 'Restaurant')
    PendingRestaurant = apps.get_model('restaurant', 'PendingRestaurant')
    
    # Process Restaurant data
    total_restaurants = Restaurant.objects.count()
    processed_restaurants = 0
    errors_restaurants = 0
    
    print(f"Starting encryption of {total_restaurants} restaurants...")
    
    for restaurant in Restaurant.objects.all().iterator(chunk_size=100):
        try:
            # Get original field values if they exist
            original_address = restaurant.address if hasattr(restaurant, 'address') and restaurant.address else None
            original_phone = restaurant.phone if hasattr(restaurant, 'phone') and restaurant.phone else None
            original_email = restaurant.email if hasattr(restaurant, 'email') and restaurant.email else None
            
            # Encrypt and store in new fields
            if original_address:
                restaurant._address_encrypted = EncryptionManager.encrypt(original_address)
            
            if original_phone:
                restaurant._phone_encrypted = EncryptionManager.encrypt(original_phone)
            
            if original_email:
                restaurant._email_encrypted = EncryptionManager.encrypt(original_email)
            
            restaurant.save()
            processed_restaurants += 1
            
            if processed_restaurants % 10 == 0:
                print(f"Processed {processed_restaurants}/{total_restaurants} restaurants...")
                
        except Exception as e:
            errors_restaurants += 1
            print(f"Error encrypting restaurant {restaurant.id}: {str(e)}")
            continue
    
    print(f"Restaurant encryption complete! Processed: {processed_restaurants}, Errors: {errors_restaurants}")
    
    # Process PendingRestaurant data
    total_pending = PendingRestaurant.objects.count()
    processed_pending = 0
    errors_pending = 0
    
    print(f"Starting encryption of {total_pending} pending restaurants...")
    
    for pending in PendingRestaurant.objects.all().iterator(chunk_size=100):
        try:
            # Get original field values
            original_address = pending.address if hasattr(pending, 'address') and pending.address else None
            original_phone = pending.phone if hasattr(pending, 'phone') and pending.phone else None
            original_email = pending.email if hasattr(pending, 'email') and pending.email else None
            
            # Encrypt and store in new fields
            if original_address:
                pending._address_encrypted = EncryptionManager.encrypt(original_address)
            
            if original_phone:
                pending._phone_encrypted = EncryptionManager.encrypt(original_phone)
            
            if original_email:
                pending._email_encrypted = EncryptionManager.encrypt(original_email)
            
            pending.save()
            processed_pending += 1
            
            if processed_pending % 10 == 0:
                print(f"Processed {processed_pending}/{total_pending} pending restaurants...")
                
        except Exception as e:
            errors_pending += 1
            print(f"Error encrypting pending restaurant {pending.id}: {str(e)}")
            continue
    
    print(f"Pending restaurant encryption complete! Processed: {processed_pending}, Errors: {errors_pending}")


def reverse_encryption(apps, schema_editor):
    """
    Reverse migration - decrypt restaurant data back to plaintext.
    
    WARNING: This should only be used if you need to rollback the encryption system.
    """
    from core.encryption import EncryptionManager
    
    Restaurant = apps.get_model('restaurant', 'Restaurant')
    PendingRestaurant = apps.get_model('restaurant', 'PendingRestaurant')
    
    print("Decrypting restaurants back to plaintext...")
    
    for restaurant in Restaurant.objects.all():
        try:
            if restaurant._address_encrypted:
                restaurant.address = EncryptionManager.decrypt(restaurant._address_encrypted)
            if restaurant._phone_encrypted:
                restaurant.phone = EncryptionManager.decrypt(restaurant._phone_encrypted)
            if restaurant._email_encrypted:
                restaurant.email = EncryptionManager.decrypt(restaurant._email_encrypted)
            restaurant.save()
        except Exception as e:
            print(f"Error decrypting restaurant {restaurant.id}: {str(e)}")
            continue
    
    print("Decrypting pending restaurants back to plaintext...")
    
    for pending in PendingRestaurant.objects.all():
        try:
            if pending._address_encrypted:
                pending.address = EncryptionManager.decrypt(pending._address_encrypted)
            if pending._phone_encrypted:
                pending.phone = EncryptionManager.decrypt(pending._phone_encrypted)
            if pending._email_encrypted:
                pending.email = EncryptionManager.decrypt(pending._email_encrypted)
            pending.save()
        except Exception as e:
            print(f"Error decrypting pending restaurant {pending.id}: {str(e)}")
            continue


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0009_add_encrypted_fields'),
    ]
    
    operations = [
        migrations.RunPython(
            encrypt_existing_restaurant_data,
            reverse_code=reverse_encryption
        ),
    ]
