"""
Management command to restore a PostgreSQL database from backup.

This command provides functionality to restore a PostgreSQL database
from various backup formats including SQL dumps, custom format backups,
and directory format backups generated by pg_dump.
"""
import os
import subprocess
from pathlib import Path
from django.conf import settings
from django.core.management.base import BaseCommand, CommandError
from django.utils import timezone

class Command(BaseCommand):
    """
    Command to restore a PostgreSQL database from a backup file.
    
    This command uses pg_restore (or psql for plain SQL files) to restore
    a PostgreSQL database from a previously created backup file.
    """
    help = 'Restore a PostgreSQL database from a backup file'
    
    def add_arguments(self, parser):
        """
        Add command line arguments for the restore command.
        
        Args:
            parser: ArgumentParser instance for adding command arguments
            
        This function defines what command-line options are available when
        running the restore_postgres command.
        """
        parser.add_argument(
            'backup_file',
            help='Path to the backup file to restore from'
        )
        parser.add_argument(
            '--clean',
            action='store_true',
            help='Clean (drop) database objects before recreating'
        )
        parser.add_argument(
            '--create',
            action='store_true',
            help='Create the database before restoring into it'
        )
        parser.add_argument(
            '--no-owner',
            action='store_true',
            help='Do not set ownership of objects to match the original database'
        )
        parser.add_argument(
            '--single-transaction',
            action='store_true',
            help='Restore as a single transaction'
        )
        parser.add_argument(
            '--dry-run',
            action='store_true',
            help='Show what would be done without making any changes'
        )
    
    def handle(self, *args, **options):
        """
        Handle the command execution for PostgreSQL restore.
        
        Args:
            options: Dictionary containing command line arguments
            
        Returns:
            None
            
        This function reads database settings from Django configuration,
        builds and executes the pg_restore command with appropriate parameters,
        and handles any errors that occur during the restore process.
        """
        # Get database settings
        db_settings = settings.DATABASES['default']
        
        # Ensure required settings are available
        if db_settings['ENGINE'] != 'django.db.backends.postgresql':
            raise CommandError('This command only works with PostgreSQL databases')
        
        # Check if backup file exists
        backup_path = Path(options['backup_file']).resolve()
        if not backup_path.exists():
            raise CommandError(f'Backup file not found: {backup_path}')
        
        # Determine if this is a plain SQL file or a format that requires pg_restore
        is_plain_sql = backup_path.suffix.lower() == '.sql'
        
        # Show warning for dry run
        if options['dry_run']:
            self.stdout.write(self.style.WARNING('Running in dry-run mode - no changes will be made'))
        
        # Build the restore command
        env = os.environ.copy()
        
        # Set PGPASSWORD environment variable for password authentication
        if 'PASSWORD' in db_settings and db_settings['PASSWORD']:
            env['PGPASSWORD'] = db_settings['PASSWORD']
        
        if is_plain_sql:
            # Use psql for plain SQL files
            cmd = [
                'psql',
                '--host', db_settings.get('HOST', 'localhost'),
                '--port', str(db_settings.get('PORT', '5432')),
                '--username', db_settings.get('USER', ''),
                '--dbname', db_settings.get('NAME', ''),
                '--file', str(backup_path),
            ]
            
            if options['single_transaction']:
                cmd.append('--single-transaction')
            
        else:
            # Use pg_restore for custom, directory, or tar format backups
            cmd = [
                'pg_restore',
                '--host', db_settings.get('HOST', 'localhost'),
                '--port', str(db_settings.get('PORT', '5432')),
                '--username', db_settings.get('USER', ''),
                '--dbname', db_settings.get('NAME', ''),
            ]
            
            # Add optional arguments
            if options['clean']:
                cmd.append('--clean')
            
            if options['create']:
                cmd.append('--create')
            
            if options['no_owner']:
                cmd.append('--no-owner')
            
            if options['single_transaction']:
                cmd.append('--single-transaction')
            
            # Add backup file path
            cmd.append(str(backup_path))
        
        # Display command to be executed
        cmd_display = ' '.join(cmd)
        self.stdout.write(f'Executing: {cmd_display}')
        
        if options['dry_run']:
            self.stdout.write(self.style.SUCCESS('Dry run completed'))
            return
        
        try:
            # Run the restore command
            self.stdout.write(f'Restoring database from: {backup_path}')
            result = subprocess.run(
                cmd,
                check=True,
                capture_output=True,
                text=True,
                env=env
            )
            
            self.stdout.write(self.style.SUCCESS('Database restore completed successfully!'))
            
            # If there's any output from the command, show it
            if result.stdout:
                self.stdout.write("Command output:")
                self.stdout.write(result.stdout)
                
        except subprocess.CalledProcessError as e:
            self.stdout.write(self.style.ERROR('Restore failed!'))
            self.stdout.write(self.style.ERROR(f'Error output: {e.stderr}'))
            raise CommandError(f'Database restore failed: {e.stderr}')
        except Exception as e:
            raise CommandError(f'Error during restore: {str(e)}')
    
    def _confirm_action(self, message):
        """
        Ask for user confirmation before proceeding with a potentially destructive action.
        
        Args:
            message: Message to display to the user
            
        Returns:
            bool: True if the user confirms, False otherwise
            
        This function provides a safety check before executing operations
        that might modify or destroy existing data.
        """
        confirm = input(f'\n{message} [y/N]: ').lower()
        return confirm in ('y', 'yes')
